### ISSUE TITLE
Update Password

### ISSUE THREAD

**Issue by mnourrhan** [BuildForSDGCohort2/Team-248-Frontend#10]
- Create a form with the old password, new password and confirm password fields.
- Validate that the new password matching the password format.
- Validate that password and confirm password fields are matched.
- Submit the update password form.
- Handle displaying any errors from the backend response.
- Handle displaying success message if request success.

**Comment by mohamedsgap** [comment]
hey @mnourrhan, I think this issue is repeated, #27 is already  created and merged to the main branch! If you think this one is must to be added I can take it anyway :+1:
