### ISSUE TITLE
Create Offer

### ISSUE THREAD

**Issue by mnourrhan** [BuildForSDGCohort2/Team-248-Frontend#11]
- Create a form for creating new offer with this data 
      - Start date             - End date
      - Price per hour      - Address
      - Preferred qualifications (text)
- Validate all the required data and dates range 
- Submit the form to the backend
- Handle displaying any errors from the backend response
- Redirect to track request page if offer created successfully (the page which user can see all the applied applicants through it)

**Comment by aashrafh** [comment]
I will work on it.
